# Generated by Django 4.2.8 on 2026-04-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_sku_id_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='products_sku_id',
        ),
    ]
