# Generated by Django 4.2.7 on 2026-04-25 07:57

from django.db import migrations, models
import django.db.models.deletion


def _to_display_name(value):
    if not value:
        return 'Uncategorized'
    return str(value).replace('_', ' ').replace('-', ' ').title()


def forwards_func(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Product = apps.get_model('api', 'Product')

    uncategorized, _ = Category.objects.get_or_create(
        name='uncategorized',
        defaults={
            'display_name': 'Uncategorized',
            'description': 'Fallback category for migrated products.',
            'is_active': True,
        },
    )

    category_map = {}
    for raw_value in Product.objects.values_list('category', flat=True).distinct():
        slug = (raw_value or '').strip().lower()
        if not slug:
            category_map[raw_value] = uncategorized
            continue

        category_obj, _ = Category.objects.get_or_create(
            name=slug,
            defaults={
                'display_name': _to_display_name(slug),
                'description': '',
                'is_active': True,
            },
        )
        category_map[raw_value] = category_obj

    for product in Product.objects.all():
        category_obj = category_map.get(product.category, uncategorized)
        product.category_ref_id = category_obj.id
        product.save(update_fields=['category_ref'])


def reverse_func(apps, schema_editor):
    Product = apps.get_model('api', 'Product')

    for product in Product.objects.select_related('category_ref'):
        if product.category_ref_id:
            product.category = product.category_ref.name
        else:
            product.category = 'uncategorized'
        product.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_ref',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
